apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploye8812
  labels:
    app: autodeploye8812
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718785466884
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploye8812
  template:
    metadata:
      labels:
        app: autodeploye8812
    spec:
      containers:
        - name: autodeploye8812
          image: acrworkflow1718785466884.azurecr.io/image-workflow-1718785466884:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
