apiVersion: v1
kind: Service
metadata:
  name: autodeploye8812
  namespace: namespace-workflow-1718785466884
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploye8812
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000